import test from "node:test";
import assert from "node:assert/strict";
import { createBalldontlieClient, fetchAllCursorPages, ProviderCapabilityError } from "../lib/balldontlie.js";
import { fetchGoatRatingsPreview, joinGoatCategoryRecords, normalizeNbaSeason } from "../lib/goatRatingsImport.js";
import { normalizeSeasonStatRecord } from "../shared/seasonStats.js";

const player = (id = 1) => ({ id, first_name: `Player${id}`, last_name: "Test", position: "G", team: { id: 1, full_name: "Team One", abbreviation: "ONE" } });
const baseRecord = (id = 1, season = 2025) => ({ player: player(id), team: player(id).team, season, stats: { gp: 70, gs: 65, min: 32, pts: 20, ast: 6, tov: 2, fg_pct: .48, fg3_pct: .39, fg3a: 6, ft_pct: .85, fta: 4, oreb: 1, dreb: 5, stl: 1.2, blk: .4 } });
const current = (id = 1) => ({ id: `bdl_${id}`, name: `Player${id} Test`, source: { provider: "balldontlie", externalId: id }, active: true, overall: 75 });

function mockClient({ optionalFailure = false, requiredFailure = false } = {}) {
  let requests = 0;
  return { getMetrics: () => ({ requestCount: requests, retryCount: 0 }), async request(path, params) { requests += 1; if (path === "/players/active") return { data: params.cursor ? [] : [player(1)], meta: {} }; if (path === "/teams") return { data: [player(1).team] }; if (path.includes("season_averages/general") && params.type === "base") { if (requiredFailure) throw new Error("base unavailable"); return { data: [baseRecord()], meta: {} }; } if (optionalFailure) throw new Error("optional unavailable"); return { data: [{ ...baseRecord(), stats: { usage_percentage: .25 } }], meta: {} }; } };
}

test("missing API key fails without exposing a secret", () => assert.throws(() => createBalldontlieClient({ apiKey: "" }), /BALLDONTLIE_API_KEY is not configured/));
test("season input normalizes deterministically", () => { assert.deepEqual(normalizeNbaSeason("2025-26"), { providerSeason: 2025, season: "2025", label: "2025-26" }); assert.throws(() => normalizeNbaSeason("2025-27"), /invalid/); });
test("cursor pagination and duplicate cursor remain protected", async () => { await assert.rejects(fetchAllCursorPages(async () => ({ data: [player()], meta: { next_cursor: 1 } })), /duplicate next_cursor/); });
test("429 and 5xx responses retry with bounded metrics", async () => { let calls = 0; const client = createBalldontlieClient({ apiKey: "redacted", minimumIntervalMs: 0, maxRetries: 2, fetchImpl: async () => { calls += 1; return calls < 3 ? { ok: false, status: calls === 1 ? 429 : 500, headers: new Headers({ "retry-after": "0" }) } : { ok: true, json: async () => ({ data: [] }) }; } }); await client.request("/players/active"); assert.equal(client.getMetrics().retryCount, 2); assert.equal(client.getMetrics().requestCount, 3); });
test("provider plan denial is classified", async () => { const client = createBalldontlieClient({ apiKey: "redacted", minimumIntervalMs: 0, fetchImpl: async () => ({ ok: false, status: 403, headers: new Headers() }) }); await assert.rejects(client.request("/nba/v1/season_averages/general"), ProviderCapabilityError); });
test("timeout aborts rather than hanging", async () => { const client = createBalldontlieClient({ apiKey: "redacted", requestTimeoutMs: 5, minimumIntervalMs: 0, fetchImpl: (_url, { signal }) => new Promise((_resolve, reject) => signal.addEventListener("abort", () => reject(Object.assign(new Error("abort"), { name: "AbortError" })))) }); await assert.rejects(client.request("/players/active"), /timed out/); });
test("duplicate rows and season mismatches are reported, not overwritten", () => { const joined = joinGoatCategoryRecords({ activePlayers: [player()], season: 2025, categoryResults: { general_base: { status: "complete", data: [baseRecord(), baseRecord(), baseRecord(1, 2024)] } } }); assert.equal(joined.rows.length, 1); assert.ok(joined.findings.some((item) => item.code === "duplicate-category-record")); });
test("percentages accept decimals/percent strings and preserve missing null", () => { const common = { provider: "x", externalPlayerId: "1", season: "2025" }; assert.equal(normalizeSeasonStatRecord({ ...common, fieldGoalPercentage: "42" }).fieldGoalPercentage, .42); assert.equal(normalizeSeasonStatRecord({ ...common, fieldGoalPercentage: null }).fieldGoalPercentage, null); assert.throws(() => normalizeSeasonStatRecord({ ...common, fieldGoalPercentage: 142 }), /between 0 and 1/); });
test("live import joins identity and generates Ratings V2 preview without persistence", async () => { const result = await fetchGoatRatingsPreview({ client: mockClient(), season: 2025, currentPlayers: [current()] }); assert.equal(result.manifest.status, "complete"); assert.equal(result.players[0].id, "bdl_1"); assert.equal(result.seasonStats.length, 1); assert.ok(result.preview); assert.equal(JSON.stringify(result).includes("redacted"), false); });
test("required category failure cannot create a preview", async () => { const result = await fetchGoatRatingsPreview({ client: mockClient({ requiredFailure: true }), season: 2025, currentPlayers: [current()], categoryIds: ["general_base"] }); assert.equal(result.manifest.status, "failed"); assert.equal(result.preview, null); });
test("optional failure creates an explicit partial blocked preview", async () => { const result = await fetchGoatRatingsPreview({ client: mockClient({ optionalFailure: true }), season: 2025, currentPlayers: [current()], categoryIds: ["general_base", "general_advanced"] }); assert.equal(result.manifest.status, "partial"); assert.ok(result.preview.manifest.publication.blockers.includes("partial-provider-categories")); });
test("joined output ordering is stable by provider identity", () => { const result = joinGoatCategoryRecords({ activePlayers: [player(2), player(1)], categoryResults: {}, season: 2025 }); assert.deepEqual(result.rows.map((row) => row.player.id), [1, 2]); });
