import { useEffect, useMemo, useState } from "react";
import PageLayout from "../components/PageLayout";
import { loadCatalogPublicationState, loadRatingsPreviewManifests, loadRatingsPreviewPlayers, publishCatalog, rollbackCatalog } from "../lib/adminRatings";
import "../adminRatings.css";
import "../catalogPublication.css";
import "../goatRatingsAdmin.css";
import "../ratingsCalibration.css";

const date = (value) => value?.toDate?.().toLocaleString?.() || (value ? new Date(value).toLocaleString() : "—");
export default function AdminRatingsPreviewPage() {
  const [manifests, setManifests] = useState([]), [selectedId, setSelectedId] = useState(""), [players, setPlayers] = useState([]), [selectedPlayerId, setSelectedPlayerId] = useState("");
  const [publication, setPublication] = useState({ current: null, versions: [], history: [] }), [search, setSearch] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all"), [roleFilter, setRoleFilter] = useState(""), [tierFilter, setTierFilter] = useState(""), [positionFilter, setPositionFilter] = useState(""), [confidenceFilter, setConfidenceFilter] = useState(""), [warningFilter, setWarningFilter] = useState(""), [trendFilter, setTrendFilter] = useState(""), [resolutionFilter, setResolutionFilter] = useState(""), [rootCauseFilter, setRootCauseFilter] = useState("");
  const [dialog, setDialog] = useState(null), [version, setVersion] = useState(""), [confirmation, setConfirmation] = useState(""), [licenseBasis, setLicenseBasis] = useState(""), [busy, setBusy] = useState(false);
  const refreshPublication = () => loadCatalogPublicationState().then(setPublication);
  useEffect(() => { Promise.all([loadRatingsPreviewManifests(), loadCatalogPublicationState()]).then(([items, state]) => { setManifests(items); setSelectedId(items[0]?.id || ""); setPublication(state); }).catch(() => setError("Ratings publication data is unavailable.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selectedId) { setPlayers([]); return; } setLoading(true); loadRatingsPreviewPlayers(selectedId).then((items) => { setPlayers(items); setSelectedPlayerId(items[0]?.id || ""); }).catch(() => setError("Preview players are unavailable.")).finally(() => setLoading(false)); }, [selectedId]);
  const manifest = manifests.find((item) => item.id === selectedId), visible = useMemo(() => players.filter((player) => {
    if (!`${player.name || ""} ${player.playerId || ""}`.toLowerCase().includes(search.trim().toLowerCase())) return false;
    if (filter === "90" && player.overall < 90) return false;
    if (filter === "provisional" && player.ratingsStatus !== "provisional") return false;
    if (filter === "insufficient" && player.ratingsStatus !== "insufficient_data") return false;
    if (filter === "outliers" && !player.outliers?.length) return false;
    if (filter === "delta" && Math.abs(player.overallDelta || 0) < 5) return false;
    if (filter === "95" && player.overall < 95) return false;
    if (filter === "85" && player.overall < 85) return false;
    if (filter === "critical" && !player.outliers?.some((item) => item.severity === "CRITICAL")) return false;
    if (filter === "warnings" && !player.outliers?.some((item) => item.severity !== "CRITICAL")) return false;
    if (filter === "low-usage" && !player.outliers?.some((item) => item.reason === "LOW_USAGE_HIGH_OVR")) return false;
    if (filter === "low-minutes" && !player.outliers?.some((item) => item.reason === "LOW_MINUTES_HIGH_OVR")) return false;
    if (filter === "one-domain" && !player.outliers?.some((item) => item.reason === "ONE_DOMAIN_INFLATION")) return false;
    if (filter === "missing-data" && (player.calibrationProfile?.signals?.missingAdvanced || 0) < 4) return false;
    return (!roleFilter || player.calibrationProfile?.role === roleFilter) && (!tierFilter || player.calibrationProfile?.tier === tierFilter) && (!positionFilter || player.primaryPosition === positionFilter) && (!confidenceFilter || player.ratingsStatus === confidenceFilter) && (!warningFilter || player.outliers?.some((item) => item.code === warningFilter)) && (!trendFilter || player.calibrationProfile?.trend === trendFilter);
  }), [players, search, filter, roleFilter, tierFilter, positionFilter, confidenceFilter, warningFilter, trendFilter]), selected = players.find((player) => player.id === selectedPlayerId), top100 = useMemo(() => players.toSorted((a, b) => b.overall - a.overall || String(a.playerId).localeCompare(String(b.playerId))).slice(0, 100), [players]);
  const warningGroups = useMemo(() => Object.values(players.flatMap((player) => (player.outliers || []).map((item) => ({ ...item, affectedPlayer: player.name || player.playerId }))).reduce((groups, item) => { const key = item.code || item.reason; if (!groups[key]) groups[key] = { code: key, severity: item.severity, title: item.title || key, explanation: item.explanation, suggestedArea: item.suggestedArea, count: 0, players: [] }; groups[key].count += 1; groups[key].players.push({ name: item.affectedPlayer, values: item.relevantValues }); return groups; }, {})).toSorted((a, b) => (a.severity === "CRITICAL" ? -1 : 1) - (b.severity === "CRITICAL" ? -1 : 1) || b.count - a.count), [players]);
  const warningResolution = useMemo(() => (manifest?.warningResolution?.items || []).filter((item) => (!resolutionFilter || item.status === resolutionFilter) && (!rootCauseFilter || item.rootCause === rootCauseFilter)), [manifest, resolutionFilter, rootCauseFilter]);
  const openDialog = (type) => { setDialog(type); setVersion(type === "rollback" ? publication.current?.previousVersion || publication.versions[0]?.id || "" : ""); setConfirmation(""); setLicenseBasis(""); };
  const submit = async () => { setBusy(true); setError(""); try { const result = dialog === "publish" ? await publishCatalog({ importId: selectedId, version, confirmation, licensingApproval: { status: "approved", basis: licenseBasis } }) : await rollbackCatalog({ targetVersion: version, confirmation }); if (result.blockers?.length) { setError(result.blockers.map((item) => item.message).join(" ")); return; } setDialog(null); await refreshPublication(); } catch (actionError) { setError(actionError.message || "Catalog action failed."); } finally { setBusy(false); } };
  return <PageLayout><main className="ratings-admin"><header><span>OWNER TOOLS</span><h1>Ratings V2 Publication</h1><p>Preview, approve, publish, and roll back immutable player catalog versions.</p></header>
    {error && <p className="ratings-admin__error" role="alert">{error}</p>}
    <section className="ratings-admin__publication"><div><small>CURRENT VERSION</small><strong>{publication.current?.catalogVersion || "Legacy catalog"}</strong><span>Previous: {publication.current?.previousVersion || "—"}</span></div><div className="ratings-admin__actions"><button type="button" disabled={!selectedId || manifests.find((item) => item.id === selectedId)?.status !== "ready"} onClick={() => openDialog("publish")}>Publish approved preview</button><button type="button" disabled={!publication.versions.length} onClick={() => openDialog("rollback")}>Rollback</button></div></section>
    {publication.history.length > 0 && <section className="ratings-admin__history"><h2>Publication history</h2>{publication.history.map((item) => <div key={item.id}><b>{item.action}</b><span>{item.fromVersion} → {item.toVersion}</span><time>{date(item.createdAt)}</time></div>)}</section>}
    {!loading && !manifests.length && <section className="ratings-admin__empty"><h2>No staged preview</h2><p>Run the trusted Ratings V2 preview workflow first.</p></section>}
    {manifests.length > 0 && <><label className="ratings-admin__import">Preview<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{manifests.map((item) => <option value={item.id} key={item.id}>{item.season} · {item.formulaVersion} · {item.status || "legacy"} · {date(item.createdAt)}</option>)}</select></label>
      {manifest && <section className="ratings-admin__summary"><div><small>STAGING</small><b>{manifest.status || "legacy"}</b></div><div><small>WRITTEN</small><b>{manifest.writtenPlayerCount ?? manifest.playerCount ?? 0}/{manifest.expectedPlayerCount ?? manifest.playerCount ?? 0}</b></div><div><small>PLAYERS</small><b>{manifest.playerCount}</b></div><div><small>VERIFIED</small><b>{manifest.verifiedCount}</b></div><div><small>PROVISIONAL</small><b>{manifest.provisionalCount}</b></div><div><small>INSUFFICIENT</small><b>{manifest.insufficientDataCount}</b></div><div><small>AVG DELTA</small><b>{manifest.comparisonToCurrentCatalog?.averageOverallDelta ?? 0}</b></div><div><small>CRITICAL</small><b>{manifest.anomalySummary?.criticalCount || 0}</b></div><footer><span>{manifest.validationStatus}</span><span>License: {manifest.licensingCheckpoint?.status}</span><span>{manifest.status === "failed" ? `Failure: ${manifest.stagingFailure?.message || "Staging did not complete."}` : manifest.status !== "ready" ? "Preview is not publishable until staging is ready." : manifest.publication?.publishedVersion ? `Published as ${manifest.publication.publishedVersion}` : (manifest.publication?.blockers || []).join(", ") || "Awaiting approval"}</span></footer></section>}
      {manifest?.calibrationRealism && <section className="ratings-admin__realism"><div><small>REALISM SCORE</small><strong>{manifest.calibrationRealism.realismScore}</strong></div><div><small>CRITICAL</small><strong>{manifest.calibrationRealism.criticalIssues?.length || 0}</strong></div><div><small>WARNINGS</small><strong>{manifest.calibrationRealism.warnings?.length || 0}</strong></div><div className="ratings-admin__position-distribution"><small>POSITION AVERAGES</small><span>{Object.entries(manifest.calibrationRealism.positionAverages || {}).map(([key, value]) => `${key} ${value}`).join(" · ") || "—"}</span></div></section>}
      {warningGroups.length > 0 && <section className="ratings-admin__warning-groups"><header><div><small>V2.4 REVIEW QUEUE</small><h2>Grouped hierarchy warnings</h2></div><span>{warningGroups.reduce((sum, group) => sum + group.count, 0)} findings</span></header><div className="ratings-admin__warning-filters"><select aria-label="Warning type filter" value={warningFilter} onChange={(event) => setWarningFilter(event.target.value)}><option value="">All warning types</option>{warningGroups.map((group) => <option value={group.code} key={group.code}>{group.title}</option>)}</select><select aria-label="Trend filter" value={trendFilter} onChange={(event) => setTrendFilter(event.target.value)}><option value="">All trends</option>{[...new Set(players.map((player) => player.calibrationProfile?.trend).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select></div><div>{warningGroups.map((group) => <article key={group.code} className={warningFilter === group.code ? "is-active" : ""}><button type="button" onClick={() => setWarningFilter(warningFilter === group.code ? "" : group.code)}><span>{group.severity} · {group.code}</span><strong>{group.title}</strong><p>{group.explanation}</p><small>{group.count} players · Review {group.suggestedArea}</small></button><details><summary>Affected players</summary>{group.players.map((player) => <p key={player.name}><b>{player.name}</b><small>{JSON.stringify(player.values || {})}</small></p>)}</details></article>)}</div></section>}
      {manifest?.warningResolution && <section className="ratings-admin__warning-resolution"><header><div><small>V2.4 → V2.4.1</small><h2>Warning resolution</h2></div><strong>{manifest.warningResolution.resolvedCount} resolved · {manifest.warningResolution.unresolvedCount} unresolved</strong></header><div className="ratings-admin__warning-filters"><select aria-label="Resolution filter" value={resolutionFilter} onChange={(event) => setResolutionFilter(event.target.value)}><option value="">All resolution states</option><option value="resolved">Resolved</option><option value="unresolved">Unresolved</option></select><select aria-label="Root cause filter" value={rootCauseFilter} onChange={(event) => setRootCauseFilter(event.target.value)}><option value="">All root causes</option>{[...new Set((manifest.warningResolution.items || []).map((item) => item.rootCause).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select></div><div>{warningResolution.map((item) => <article key={`${item.playerId}-${item.code}`}><span>{item.status} · {item.code}</span><strong>{item.name}</strong><p>{item.previousOverall} → {item.newOverall} OVR · {item.newRole} · {item.newArchetype}</p><small>{item.trend} · gravity {item.shootingGravity ?? "—"} · evidence {item.evidence ?? "—"}</small></article>)}</div></section>}
      {manifest?.fetchManifest && <section className="ratings-admin__fetch"><div><small>LIVE FETCH</small><b>{manifest.fetchManifest.status}</b></div><span>{manifest.fetchManifest.requestCount} requests · {manifest.fetchManifest.retryCount} retries · {manifest.fetchManifest.durationMs}ms</span><span>{manifest.fetchManifest.activePlayerCount} active players</span><span>{manifest.fetchManifest.optionalMissingCategories?.length ? `Missing: ${manifest.fetchManifest.optionalMissingCategories.join(", ")}` : "All requested categories complete"}</span></section>}
      <div className="ratings-admin__filters"><select aria-label="Rating review filter" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All players</option><option value="critical">Critical</option><option value="warnings">Warnings</option><option value="90">90+</option><option value="85">85+</option><option value="low-usage">Low usage</option><option value="low-minutes">Low minutes</option><option value="one-domain">One domain</option><option value="missing-data">Missing data</option><option value="delta">Large delta</option><option value="provisional">Provisional</option><option value="insufficient">Insufficient</option></select><select aria-label="Role filter" value={roleFilter} onChange={(event) => setRoleFilter(event.target.value)}><option value="">All roles</option>{[...new Set(players.map((player) => player.calibrationProfile?.role).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Tier filter" value={tierFilter} onChange={(event) => setTierFilter(event.target.value)}><option value="">All tiers</option>{[...new Set(players.map((player) => player.calibrationProfile?.tier).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Position filter" value={positionFilter} onChange={(event) => setPositionFilter(event.target.value)}><option value="">All positions</option>{[...new Set(players.map((player) => player.primaryPosition).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Confidence filter" value={confidenceFilter} onChange={(event) => setConfidenceFilter(event.target.value)}><option value="">All confidence</option><option value="verified">Verified</option><option value="provisional">Provisional</option><option value="insufficient_data">Insufficient</option></select></div>
      <details className="ratings-admin__top-table"><summary>Top 100 hierarchy</summary><div><span>RK</span><span>PLAYER</span><span>ROLE</span><span>POS</span><span>OVR</span>{top100.map((player, index) => <button type="button" key={player.id} onClick={() => setSelectedPlayerId(player.id)}><b>{index + 1}</b><span>{player.name || player.playerId}</span><small>{player.calibrationProfile?.role || "—"}</small><small>{player.primaryPosition || "—"}</small><strong>{player.overall}</strong></button>)}</div></details>
      <div className="ratings-admin__workspace"><section className="ratings-admin__list"><input aria-label="Search preview players" placeholder="Search player" value={search} onChange={(event) => setSearch(event.target.value)}/>{visible.map((player) => <button className={selectedPlayerId === player.id ? "is-active" : ""} type="button" key={player.id} onClick={() => setSelectedPlayerId(player.id)}><span><b>{player.name || player.playerId}</b><small>#{player.populationRank || "—"} · {player.primaryPosition || player.normalizedInput?.primaryPosition} #{player.positionRank || "—"} · {player.calibrationProfile?.role || player.ratingsStatus}</small></span><strong>{player.overall}</strong></button>)}</section><section className="ratings-admin__inspector">{selected ? <><header><span>{selected.ratingsSource} · {selected.ratingsSeason}</span><h2>{selected.name || selected.playerId}</h2><strong>{selected.overall} OVR</strong><p>{selected.calibrationProfile?.role} · {selected.calibrationProfile?.tier} · #{selected.populationRank} overall · #{selected.positionRank} {selected.primaryPosition}</p><p>{selected.ratingsConfidence?.level} confidence · {Math.round((selected.ratingsConfidence?.score || 0) * 100)}% · V2.1 delta {selected.overallDelta > 0 ? "+" : ""}{selected.overallDelta ?? "—"}</p></header>{selected.calibrationProfile && <section className="ratings-admin__explanation"><div><b>Why</b><span>{selected.calibrationProfile.explanation?.strengths?.join(" · ") || "balanced production profile"}</span></div><div><b>Limiters</b><span>{selected.calibrationProfile.explanation?.limiters?.join(" · ") || "none identified"}</span></div></section>}{selected.outliers?.length > 0 && <aside><b>Review queue</b>{selected.outliers.map((item) => <p key={item.reason}>{item.severity} · {item.reason} · {item.suggestedArea}</p>)}</aside>}<div className="ratings-admin__ratings">{Object.entries(selected.ratings || {}).filter(([, value]) => Number.isInteger(value)).map(([key, value]) => <div key={key}><span>{key}</span><b>{value}</b><small>{selected.explanations?.[key]?.signals?.join(" · ")}</small></div>)}</div></> : <p>Select a player.</p>}</section></div></>}
    {dialog && <div className="ratings-admin__dialog-backdrop"><section className="ratings-admin__dialog" role="dialog" aria-modal="true" aria-labelledby="catalog-action-title"><h2 id="catalog-action-title">{dialog === "publish" ? "Publish immutable catalog" : "Rollback current pointer"}</h2><p>{dialog === "publish" ? "Creates and verifies a new version before atomically activating it." : "Only the current pointer changes; historical versions remain immutable."}</p><label>Catalog version<input value={version} onChange={(event) => setVersion(event.target.value)} placeholder="2026.1" /></label>{dialog === "publish" && <label>Licensing approval basis<textarea value={licenseBasis} onChange={(event) => setLicenseBasis(event.target.value)} placeholder="Approved license/review basis" /></label>}<label>Confirmation<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder={`${dialog === "publish" ? "PUBLISH" : "ROLLBACK"} ${version || "VERSION"}`} /></label><footer><button type="button" onClick={() => setDialog(null)}>Cancel</button><button type="button" disabled={busy} onClick={submit}>{busy ? "Working…" : dialog === "publish" ? "Publish" : "Rollback"}</button></footer></section></div>}
  </main></PageLayout>;
}
