import { useEffect, useMemo, useState } from "react";
import PageLayout from "../../components/PageLayout";
import RatingsReviewPanel from "../../components/admin/ratings/RatingsReviewPanel";
import { loadCatalogPublicationState, loadRatingsPreviewManifests, loadRatingsPreviewPlayers, loadRatingsReviewHistory, publishCatalog, rollbackCatalog } from "../../lib/adminRatings";
import "../../adminRatings.css";
import "../../catalogPublication.css";
import "../../goatRatingsAdmin.css";
import "../../ratingsCalibration.css";

const date = (value) => value?.toDate?.().toLocaleString?.() || (value ? new Date(value).toLocaleString() : "—");
const team = (player) => { const value = player.team || player.normalizedInput?.team; return player.team?.abbreviation || player.normalizedInput?.teamAbbreviation || value?.abbreviation || value?.name || (typeof value === "string" ? value : "—"); };
const role = (player) => player.calibrationProfile?.role || "—";
const confidence = (player) => player.ratingsConfidence?.level || player.ratingsStatus || "—";

export default function AdminRatingsPreviewPage() {
  const [manifests, setManifests] = useState([]), [selectedId, setSelectedId] = useState(""), [players, setPlayers] = useState([]), [reviewHistory, setReviewHistory] = useState([]);
  const [publication, setPublication] = useState({ current: null, versions: [], history: [] }), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""), [position, setPosition] = useState(""), [ratingFloor, setRatingFloor] = useState(0), [confidenceFilter, setConfidenceFilter] = useState(""), [warningsOnly, setWarningsOnly] = useState(false);
  const [roleFilter, setRoleFilter] = useState(""), [tierFilter, setTierFilter] = useState(""), [trendFilter, setTrendFilter] = useState(""), [advancedFlag, setAdvancedFlag] = useState(""), [archetypeFilter, setArchetypeFilter] = useState(""), [warningCode, setWarningCode] = useState("");
  const [dialog, setDialog] = useState(null), [version, setVersion] = useState(""), [confirmation, setConfirmation] = useState(""), [licenseBasis, setLicenseBasis] = useState(""), [busy, setBusy] = useState(false);
  const currentCandidate = manifests.find((item) => item.formulaVersion === "ratings-v2.4.1" && item.status === "ready") || manifests[0];
  const manifest = manifests.find((item) => item.id === selectedId);
  const refreshPublication = () => loadCatalogPublicationState().then(setPublication);
  const refreshReviews = async () => { const [items, events] = await Promise.all([loadRatingsPreviewManifests(), loadRatingsReviewHistory(selectedId)]); setManifests(items); setReviewHistory(events); };
  useEffect(() => { Promise.all([loadRatingsPreviewManifests(), loadCatalogPublicationState()]).then(([items, state]) => { setManifests(items); setSelectedId((items.find((item) => item.formulaVersion === "ratings-v2.4.1" && item.status === "ready") || items[0])?.id || ""); setPublication(state); }).catch(() => setError("Ratings publication data is unavailable.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selectedId) { setPlayers([]); setReviewHistory([]); return; } setLoading(true); Promise.all([loadRatingsPreviewPlayers(selectedId), loadRatingsReviewHistory(selectedId)]).then(([items, events]) => { setPlayers(items); setReviewHistory(events); }).catch(() => setError("Preview players or review history are unavailable.")).finally(() => setLoading(false)); }, [selectedId]);
  const topPlayers = useMemo(() => players.toSorted((a, b) => b.overall - a.overall || String(a.playerId).localeCompare(String(b.playerId))).slice(0, 12), [players]);
  const summary = useMemo(() => ({ average: players.length ? Math.round(players.reduce((sum, player) => sum + player.overall, 0) / players.length * 100) / 100 : 0, maximum: players.length ? Math.max(...players.map((player) => player.overall)) : 0, ninety: players.filter((player) => player.overall >= 90).length }), [players]);
  const visible = useMemo(() => players.filter((player) => {
    const text = `${player.name || ""} ${player.playerId || ""}`.toLowerCase();
    if (!text.includes(search.trim().toLowerCase()) || (position && player.primaryPosition !== position) || player.overall < ratingFloor || (confidenceFilter && confidence(player) !== confidenceFilter) || (warningsOnly && !player.outliers?.length)) return false;
    if (roleFilter && role(player) !== roleFilter || tierFilter && player.calibrationProfile?.tier !== tierFilter || trendFilter && player.calibrationProfile?.trend !== trendFilter || archetypeFilter && player.calibrationProfile?.archetype !== archetypeFilter || warningCode && !player.outliers?.some((item) => (item.code || item.reason) === warningCode)) return false;
    if (advancedFlag === "delta" && Math.abs(player.overallDelta || 0) < 5 || advancedFlag === "low-usage" && !player.outliers?.some((item) => item.reason === "LOW_USAGE_HIGH_OVR") || advancedFlag === "low-minutes" && !player.outliers?.some((item) => item.reason === "LOW_MINUTES_HIGH_OVR") || advancedFlag === "missing-data" && (player.calibrationProfile?.signals?.missingAdvanced || 0) < 4) return false;
    return true;
  }), [players, search, position, ratingFloor, confidenceFilter, warningsOnly, roleFilter, tierFilter, trendFilter, advancedFlag, archetypeFilter, warningCode]);
  const reviewsReady = manifest?.status === "ready" && manifest?.reviews?.calibration?.status === "approved" && manifest?.reviews?.licensing?.status === "approved" && !(manifest?.anomalySummary?.criticalCount > 0);
  const publicationCandidate = publication.versions.find((item) => ["publishing", "failed"].includes(item.status) && item.sourceImportId === selectedId);
  const openDialog = (type) => { setDialog(type); setVersion(type === "rollback" ? publication.current?.previousVersion || publication.versions.find((item) => item.status === "published")?.id || "" : ""); setConfirmation(""); setLicenseBasis(""); };
  const submit = async () => { setBusy(true); setError(""); try { const result = dialog === "publish" ? await publishCatalog({ importId: selectedId, version, confirmation, licensingApproval: { basis: licenseBasis } }) : await rollbackCatalog({ targetVersion: version, confirmation }); if (result.blockers?.length) { setError(result.blockers.map((item) => item.message).join(" ")); return; } setDialog(null); await refreshPublication(); } catch (actionError) { const timedOut = String(actionError.code || actionError.message).includes("deadline-exceeded"); setError(timedOut ? "Catalog publication timed out before completion. The current catalog was not changed. You may safely retry after checking publication status." : actionError.message || "Catalog action failed."); await refreshPublication().catch(() => {}); } finally { setBusy(false); } };
  return <PageLayout><main className="ratings-admin ratings-admin--simple">
    <header><span>OWNER TOOLS</span><h1>Ratings Review</h1><p>Review the current candidate, approve it, and publish one immutable catalog.</p></header>
    {error && <p className="ratings-admin__error" role="alert">{error}</p>}
    {!loading && !manifests.length && <section className="ratings-admin__empty"><h2>No staged preview</h2><p>Run the trusted Ratings V2 staging workflow first.</p></section>}
    {manifest && <>
      <section className="ratings-candidate"><div><small>CURRENT CANDIDATE</small><strong>{currentCandidate?.id === selectedId ? selectedId : "Previous import"}</strong><span>{manifest.formulaVersion} · staged {date(manifest.createdAt)}</span></div><details><summary>Previous Imports</summary><select aria-label="Ratings import" value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{manifests.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.formulaVersion} · {item.status}</option>)}</select></details></section>
      <section className="ratings-health" aria-label="Candidate health"><div><small>FORMULA</small><b>{manifest.formulaVersion}</b></div><div><small>IMPORT</small><b>{manifest.status}</b></div><div><small>PLAYERS</small><b>{manifest.playerCount || players.length}</b></div><div><small>CRITICAL</small><b>{manifest.anomalySummary?.criticalCount || 0}</b></div><div><small>UNRESOLVED</small><b>{manifest.warningResolution?.unresolvedCount || 0}</b></div><div><small>AVG OVR</small><b>{summary.average}</b></div><div><small>MAX OVR</small><b>{summary.maximum}</b></div><div><small>90+</small><b>{summary.ninety}</b></div><div><small>REVIEW</small><b>{reviewsReady ? "Approved" : "Pending"}</b></div><div><small>PUBLICATION</small><b>{reviewsReady ? "Ready" : "Blocked"}</b></div></section>
      <section className="ratings-top"><header><div><small>HIERARCHY CHECK</small><h2>Top Players</h2></div><span>{topPlayers.length} shown</span></header><div>{topPlayers.map((player, index) => <article key={player.id}><b>{index + 1}</b><span><strong>{player.name}</strong><small>{team(player)} · {player.primaryPosition} · {role(player)}</small></span><em>{player.overall}</em></article>)}</div></section>
      <section className="ratings-player-browser"><header><div><small>PLAYER REVIEW</small><h2>Search Players</h2></div><span>{visible.length} results</span></header><div className="ratings-player-filters"><input aria-label="Search players" placeholder="Search player" value={search} onChange={(event) => setSearch(event.target.value)}/><select aria-label="Position" value={position} onChange={(event) => setPosition(event.target.value)}><option value="">All positions</option>{[...new Set(players.map((player) => player.primaryPosition).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><button type="button" className={ratingFloor === 90 ? "is-active" : ""} onClick={() => setRatingFloor(ratingFloor === 90 ? 0 : 90)}>90+</button><button type="button" className={ratingFloor === 85 ? "is-active" : ""} onClick={() => setRatingFloor(ratingFloor === 85 ? 0 : 85)}>85+</button><select aria-label="Confidence" value={confidenceFilter} onChange={(event) => setConfidenceFilter(event.target.value)}><option value="">All confidence</option>{[...new Set(players.map(confidence))].map((value) => <option key={value}>{value}</option>)}</select><button type="button" className={warningsOnly ? "is-active" : ""} onClick={() => setWarningsOnly(!warningsOnly)}>Warnings</button></div>
        <details className="ratings-more-filters"><summary>More Filters</summary><div><select value={roleFilter} onChange={(event) => setRoleFilter(event.target.value)}><option value="">All roles</option>{[...new Set(players.map(role))].map((value) => <option key={value}>{value}</option>)}</select><select value={tierFilter} onChange={(event) => setTierFilter(event.target.value)}><option value="">All tiers</option>{[...new Set(players.map((player) => player.calibrationProfile?.tier).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select value={trendFilter} onChange={(event) => setTrendFilter(event.target.value)}><option value="">All trends</option>{[...new Set(players.map((player) => player.calibrationProfile?.trend).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select value={archetypeFilter} onChange={(event) => setArchetypeFilter(event.target.value)}><option value="">All archetypes</option>{[...new Set(players.map((player) => player.calibrationProfile?.archetype).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select value={warningCode} onChange={(event) => setWarningCode(event.target.value)}><option value="">All warning codes</option>{[...new Set(players.flatMap((player) => player.outliers || []).map((item) => item.code || item.reason))].map((value) => <option key={value}>{value}</option>)}</select><select value={advancedFlag} onChange={(event) => setAdvancedFlag(event.target.value)}><option value="">All diagnostics</option><option value="delta">Large delta</option><option value="low-usage">Low usage</option><option value="low-minutes">Low minutes</option><option value="missing-data">Missing data</option></select></div></details>
        <div className="ratings-player-table"><div className="ratings-player-table__head"><span>Player</span><span>Team</span><span>Position</span><span>OVR</span><span>Role</span><span>Confidence</span></div>{visible.slice(0, 150).map((player) => <details key={player.id}><summary><span>{player.name || player.playerId}</span><span>{team(player)}</span><span>{player.primaryPosition}</span><b>{player.overall}</b><span>{role(player)}</span><span>{confidence(player)}</span></summary><div><p><b>Strengths:</b> {player.calibrationProfile?.explanation?.strengths?.join(" · ") || "Balanced profile"}</p><p><b>Limiters:</b> {player.calibrationProfile?.explanation?.limiters?.join(" · ") || "None identified"}</p><p><b>Trend:</b> {player.calibrationProfile?.trend || "—"} · <b>Shooting gravity:</b> {player.calibrationProfile?.shootingGravity ?? "—"} · <b>Ranks:</b> #{player.populationRank || "—"} overall / #{player.positionRank || "—"} position</p><div className="ratings-player-table__attributes">{Object.entries(player.ratings || {}).filter(([, value]) => Number.isInteger(value)).map(([key, value]) => <span key={key}>{key} <b>{value}</b></span>)}</div></div></details>)}</div>
      </section>
      <RatingsReviewPanel importId={selectedId} manifest={manifest} history={reviewHistory} onChanged={refreshReviews} onError={setError}/>
      <section className="ratings-publication"><header><div><small>ACTIVE CATALOG</small><h2>{publication.current?.catalogVersion || "Legacy catalog"}</h2></div><div><button type="button" disabled={!reviewsReady} onClick={() => openDialog("publish")}>Publish approved preview</button><button type="button" disabled={!publication.versions.some((item) => item.status === "published")} onClick={() => openDialog("rollback")}>Rollback</button></div></header>{publicationCandidate && <p>{publicationCandidate.id} · {publicationCandidate.status} · {publicationCandidate.publishedPlayerCount || 0}/{publicationCandidate.expectedPlayerCount || 0} players</p>}</section>
      <details className="ratings-advanced"><summary>Advanced Details</summary><div><details><summary>Coverage, normalization & catalog comparison</summary><pre>{JSON.stringify({ coverage: manifest.coverage, normalizationMetadata: manifest.normalizationMetadata, comparisonToCurrentCatalog: manifest.comparisonToCurrentCatalog }, null, 2)}</pre></details><details><summary>Position, confidence, trend, role & tier diagnostics</summary><pre>{JSON.stringify({ positionAverages: manifest.calibrationRealism?.positionAverages, ratingDistribution: manifest.ratingDistribution, realism: manifest.calibrationRealism }, null, 2)}</pre></details><details><summary>Anomalies, warning history & formula deltas</summary><pre>{JSON.stringify({ anomalySummary: manifest.anomalySummary, warningResolution: manifest.warningResolution }, null, 2)}</pre></details><details><summary>Provider, category & staging metadata</summary><pre>{JSON.stringify({ fetchManifest: manifest.fetchManifest, sourceCategoryCoverage: manifest.sourceCategoryCoverage, staging: { expectedPlayerCount: manifest.expectedPlayerCount, writtenPlayerCount: manifest.writtenPlayerCount, stagedPlayerCount: manifest.stagedPlayerCount, stagingVersion: manifest.stagingVersion } }, null, 2)}</pre></details>{publication.history.length > 0 && <details><summary>Publication history</summary><pre>{JSON.stringify(publication.history, null, 2)}</pre></details>}</div></details>
    </>}
    {dialog && <div className="ratings-admin__dialog-backdrop"><section className="ratings-admin__dialog" role="dialog" aria-modal="true"><h2>{dialog === "publish" ? "Publish immutable catalog" : "Rollback current pointer"}</h2><label>Catalog version<input value={version} onChange={(event) => setVersion(event.target.value)} placeholder="2026.1"/></label>{dialog === "publish" && <label>Licensing approval basis<textarea value={licenseBasis} onChange={(event) => setLicenseBasis(event.target.value)}/></label>}<label>Confirmation<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder={`${dialog === "publish" ? "PUBLISH" : "ROLLBACK"} ${version || "VERSION"}`}/></label><footer><button type="button" onClick={() => setDialog(null)}>Cancel</button><button type="button" disabled={busy} onClick={submit}>{busy ? "Working…" : dialog === "publish" ? "Publish" : "Rollback"}</button></footer></section></div>}
  </main></PageLayout>;
}
